title: Programming the Past Workbook
description: Coursebook for HIS4936, Programming the Past, at the University of South Florida
repository: thePortus/programming-the-past
include:
  - 404.md
  - index.md
  - author.md
  - setup.md
  - lessons/week-1.md
  - lessons/week-2.md
  - lessons/week-3.md
  - lessons/week-4.md
  - lessons/week-5.md
  - lessons/week-6.md
  - lessons/week-7.md
  - lessons/week-8.md
  - lessons/week-9.md
  - lessons/week-10.md
  - lessons/week-11.md
  - lessons/week-12.md
  - lessons/week-13.md
  - lessons/week-14.md
  - lessons/week-15.md
plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
source: ./pages
collections_dir: ./pages
includes_dir: _includes
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "sunrise" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
