title: Programming the Past Course Workbook
description: Coursebook for HIS4936, Programming the Past, at the University of South Florida
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - setup.md
# built in default GitHub pages theme disabled
# theme: jekyll-theme-dinky
# visit https://jekyllthemes.org for other remote themes
remote_theme: murraco/jekyll-theme-minimal-resume
source: ./pages
collections_dir: ./pages
includes_dir: _includes
